### ISSUE TITLE
Add option for latest caret version

### ISSUE THREAD

**Issue by theetrain** [Anifacted/lerna-update-wizard#27]
Hello, thanks for developing this tool.

When I upgrade a dependency, I'd like the option for 'latest installed' and to bump the caret version in each respective package.json as well.

For example:

**My packages**
```
Component1
  package.json
    - prop-types@^15.6.1
Component2
  package.json
  - prop-types@^15.6.2
```

**Run `lernaupdate`**
```sh
Lerna Update Wizard
v0.9.4

Starting update wizard for project

? Select a dependency to upgrade: prop-types (1 version)

? Select packages to affect: Component1, Component2
? Select version to install: (Use arrow keys)
❯ ^15.6.2 #latest with caret version
  15.6.2 #latest
  15.5.0-alpha.0 #dev
  15.5.7-alpha.1 #next
  ^15.6.1 Highest installed
```

By updating the version string in each package's `package.json`, this helps prevent the appearance of `node_modules` directories nested inside a package with an outdated dependency, when using Yarn Workspaces with Lerna.

I'm willing to help contribute a solution for this.

**Comment by Anifacted** [comment]
Hey, thanks for the input. This is a valuable suggestion and it is something that has crossed my mind as well.

I am not sure I would want the with-caret-option to only be available for the latest version, but rather something the user could decide for any version selected.
There's a bit of a UI challenge in this one. A PR is certainly welcome. I may give it a shot to find a solution to this myself as well :)

**Comment by Anifacted** [comment]
@theetrain as of version `0.10.0` it is now possible to specify `^` and `~` semver prefixes on the target dependency version (by using the arrow keys). Let me know if this solves your issue.

![semver](https://user-images.githubusercontent.com/6997051/49310911-fa5bba80-f4df-11e8-95f1-6f7466149978.gif)

**Comment by Anifacted** [comment]
Awesome 👍

**Comment by jhwegener** [comment]
Onyl works with this for non caret version: https://stackoverflow.com/a/30659125

**Comment by Anifacted** [comment]
@jhwegener good to know. I suppose the script should take this into consideration, ideally.

**Comment by jhwegener** [comment]
@Anifacted this would be a good idea!
