### ISSUE TITLE
`lernaupdate` command not found

### ISSUE THREAD

**Issue by Marjona6** [Anifacted/lerna-update-wizard#34]
I've installed `lerna-update-wizard` as recommended (as a devDependency), and once it is installed, running `lernaupdate` from terminal returns a message of `command not found`:

```
$ lernaupdate
bash: lernaupdate: command not found
```

I tried installing as a regular dependency as well and got the same result.

I'm working with a Lerna monorepo and running all of this from the root, with several packages. I'm also using `--hoist` with Lerna, but I don't think this should cause the `lernaupdate` command itself to not even be found.

**Comment by Anifacted** [comment]
Hi!

Can you please verify that the file `[your project]/node_modules/.bin/lernaupdate` exists? If it does, it would seem that your shell is not looking for executables in this directory.

One way to fix this is to export the directory in your `$PATH` environment variables like so:
(Assuming you are using a UNIX machine)
```bash
export PATH="$PATH:./node_modules/.bin"
```

The recommended strategy is to use a node version manager, though, such as NVM, which should take care of this issue for you.

You can also try to install lerna-update-wizard globally:

```bash
npm install -g lerna-update-wizard
```

Please let me know if this does not resolve your issue.

**Comment by Marjona6** [comment]
Hi, thanks for your quick reply!

`export PATH="$PATH:./node_modules/.bin"` worked perfectly. Thanks for your help and for this awesome resource!

**Comment by Anifacted** [comment]
Awesome, thank you for using it 😃👍

**Comment by jpettit** [comment]
This should also just easily be run via `npx lernaupdate`.  I still had the same issue with an `npm i --save-dev lerna-update-wizard` not actually working out of the box.
