### ISSUE TITLE
Updating with peerdependency end installing dependecies 

### ISSUE THREAD

**Issue by nahumzs** [Anifacted/lerna-update-wizard#40]
Awesome script, I have been running into an issue. Maybe I don't understand quite correctly but I have been trying to update a react as `peer denpendency`, but when I run the script and I select `peer dependecy`  the script write down the update under dependencies, which is not what I'm expecting.

I have something like this:
```json
{
  "name": "@myOrg/button",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "peerDependencies": {
    "react": "^16.7.0",
    "styled-components": "^4.1.3"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "publishConfig": {
    "access": "public"
  },
  "author": "@",
  "license": "MIT"
}
```

after updating to peer dependecy ends like:
```json
{
  "name": "@myOrg/button",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "peerDependencies": {
    "react": "^16.7.0",
    "styled-components": "^4.1.3"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "publishConfig": {
    "access": "public"
  },
  "author": "@",
  "license": "MIT",
  "dependencies": {
    "react": "16.8.6",
    "styled-components": "4.2.0"
  }
}
```

Do you have any idea what am I possible doing wrong?

**Comment by Anifacted** [comment]
Hmm, yes that sounds unexpected. I take it that you are using Yarn then and not NPM, correct?

**Comment by nahumzs** [comment]
Yes, I'm using Yarn indeed, anything that I could do to mitigated/solve this issue?

**Comment by Anifacted** [comment]
Ah, it seems it is not even detecting that the dependency is installed, when it is a peer dependency, instead treating it as a new dependency to be added. This is a bug. I will have a look!

**Comment by Anifacted** [comment]
Closing since v0.15.0 adds full support for peer dependencies 👍
