### ISSUE TITLE
Support for multiple in dependency install at one time

### ISSUE THREAD

**Issue by hannadrehman** [Anifacted/lerna-update-wizard#46]
i love this tool. but when updating dependency i have to search one by one and install one at a time . it would be really awesome if we select all dependencies to install . and in one go it updates/installs them all

it would be a real time saver.

**Comment by hannadrehman** [comment]
@karpov3 i am guessing it will not update `package.json`

**Comment by Anifacted** [comment]
I have a PR in the making for this feature, but it requires quite a bit of refactoring, so it's hard to find the time to get it pushed that last bit towards completion, but I will try and set aside some time in the coming week to finish it up 👍

**Comment by hannadrehman** [comment]
that would be really cool. thanks a lot. @Anifacted

**Comment by Anifacted** [comment]
@hannadrehman As of `v0.17.0` it is now possible to install multiple dependencies per session. I.e. without running the command multiple times.

![image](https://user-images.githubusercontent.com/6997051/68870224-d5fdeb80-06fa-11ea-9484-702f49f89c8b.png)

There are still improvements to do around batching and it is only supported in interactive mode for now, but it's a start :)

**Comment by hannadrehman** [comment]
@Anifacted thankyou soo much.. i tried it. and its amazing :)
