### ISSUE TITLE
Removes newline at end of package.json

### ISSUE THREAD

**Issue by cachgill** [Anifacted/lerna-update-wizard#55]
When I ran the wizard, in addition to updating the selected package version in my package.jsons, it removed the newline at the end of every file. Is there an option to leave that newline in place?

**Comment by Anifacted** [comment]
Looks like we are getting closer and closer to a clean package.json after modifying. I made it less intrusive the other day following this issue: https://github.com/Anifacted/lerna-update-wizard/issues/51. But it would seem we are not 100% there yet 😅 I will make a PR that makes it leave a newline in the file if the file already has one 👍

**Comment by cachgill** [comment]
Locally, in runJob, what I wrote to the package.json file was the original file with everything between the first open bracket and the last closed bracket with the return value of modifyPackageJson. That's probably overkill just to reintroduce a newline if it exists, and it would probably be easier to just check if the last line of the original file is a newline character.

**Comment by Anifacted** [comment]
Have a PR on the way for this: https://github.com/Anifacted/lerna-update-wizard/pull/57

**Comment by Anifacted** [comment]
Should be fixed in  `0.17.4`. Please close this issue if you can confirm that it solved the problem :)
