### ISSUE TITLE
Does not update both the same dependency as both a peerDependency and a devDependency in the same package.json

### ISSUE THREAD

**Issue by cachgill** [Anifacted/lerna-update-wizard#58]
If a package.json has both a peerDependency and a devDependency field, and the same dependency is in both lists, only one of them will be updated, e.g. if updating "foo" to version "2.0.0":

```
{
  "peerDependencies": {
    "foo": "1.0.0" ==> "2.0.0"
  },
  "devDependencies": {
    "foo": "1.0.0" ==> "1.0.0"
  }
}
```

**Comment by cachgill** [comment]
This is when lernaupdate is run with just the --lazy flag.

**Comment by Anifacted** [comment]
Right. I suppose the expected behavior should be that both are updated. If it were only one of the, I'd expect it to be the `devDependencies` to be updated and the `peerDependencies` to be unchanged.

**Comment by cachgill** [comment]
Before I close out this ticket, can you bump the version number?

**Comment by Anifacted** [comment]
I am seeing some issues with the tests failing on the latest `master` which I need to resolve first. Will publish as soon as they are 👍

**Comment by Anifacted** [comment]
Published!

**Comment by cachgill** [comment]
Thanks!

**Comment by Anifacted** [comment]
Thank you for the contribution :)
