### ISSUE TITLE
Removes version range (caret)

### ISSUE THREAD

**Issue by RusinovAnton** [Anifacted/lerna-update-wizard#59]
![image](https://user-images.githubusercontent.com/13165540/69239881-ec48f300-0ba3-11ea-9f4f-475a3cd39e06.png)

**Comment by Anifacted** [comment]
What's the flow that you went through? You can control the version carets via the left/right arrows on the version screen:

![semver](https://user-images.githubusercontent.com/6997051/49310911-fa5bba80-f4df-11e8-95f1-6f7466149978.gif)

**Comment by RusinovAnton** [comment]
Wow, I like the feature, and I didn't know about it - I just chose the `#latest` blindly.  

But then my confusion is in the following: why when I have `reselect@^4.0.0`, `lerna-update-wizard` suggests to me that there is a possible update?

**Comment by Anifacted** [comment]
Well, that page just lists all the published versions for the selected dependency, without taking your currently installed dependencies into account. It is not really a problem as I see it. 

In some cases, you want to align multiple packages to the same version. One or more of the selected packages will have the target version installed already, but the other won't, so it's important that it is in the list for you to select :)

**Comment by RusinovAnton** [comment]
Ok, sounds good to me. I think I just misunderstood the goal of this package, thanks for clarifications!
I'm going to use `npm/yarn outdated` for my purposes of finding packages that need to be upgraded and `lerna-update-wizard` to update any package I need.

I just wanted to share this screenshot with you. Since I have a small height of the VScode's terminal window I didn't see the tips on a version change, that's why I was confused with the caret removal

![image](https://user-images.githubusercontent.com/13165540/69243123-0934f480-0bab-11ea-9588-8cd7b4c2bd7a.png)

**Comment by Anifacted** [comment]
> I'm going to use npm/yarn outdated for my purposes of finding packages that need to be upgraded and lerna-update-wizard to update any package I need.

Sounds like a good plan :)

> I just wanted to share this screenshot with you.

Ah, thanks for sharing. Yes, I should find a way to make the tip more clear 👍
