### ISSUE TITLE
package.json updates use different indentation

### ISSUE THREAD

**Issue by tehOPEologist** [Anifacted/lerna-update-wizard#65]
when updating package.jsons, it looks like it uses 2 spaces, and in my code i'm using 4.  is there some configuration for that that i missed?  or is there not a way to adjust that currently?  ifso, could there please be an option added so that when versions are modified the whole file isn't modified?  thanks!

**Comment by Anifacted** [comment]
The reason why it is currently affecting the whole file is that it works parsing the package.json into a javascript object, then does updates/transformations and then stringifies it back into a JSON string to be written to the file (via `JSON.stringify()`).

The third argument of `JSON.stringify` is indeed the "spacer" to be used for indentation, so I suppose we could make a qualified guess on the indentation used in the file by reading the first line, and then using this in the subsequent call to rewrite the file 👍 

It all happens in here: https://github.com/Anifacted/lerna-update-wizard/blob/master/src/utils/modifyPackageJson.js

**Comment by tehOPEologist** [comment]
awesome!  i'd love to test this out whenever a version committed has this change.  thanks so much for your help and thanks for making an intuitive package mgmt cli tool!

**Comment by Anifacted** [comment]
@tehOPEologist this should be fixed now in version `0.17.7` :)

**Comment by tehOPEologist** [comment]
you're the man!  i'll be in office shortly and will update/verify and close this issue once i've confirmed it works as intended.  thanks so much again on making such a wonderful product! :D

**Comment by tehOPEologist** [comment]
just updated, looks great!  thanks again, closing

**Comment by Anifacted** [comment]
Awesome! Happy to help :)
