### ISSUE TITLE
feature request: support `packages` lerna.json option

### ISSUE THREAD

**Issue by maritz** [Anifacted/lerna-update-wizard#7]
Curently lerna-update-wizard expects the default configuration for package location, where each subdirectory of ./packages/ is a package.

However with the [packages option in lerna.json](https://github.com/lerna/lerna#lernajson) you can use other directory structures as needed.

Lerna itself uses [globby](https://github.com/sindresorhus/globby) for it, as far as I can tell: https://github.com/lerna/lerna/blob/64916d650233f939d49d34ec52c691037f89106c/utils/collect-packages/collect-packages.js

**Comment by maritz** [comment]
@lerna/collect-packages is only published for the 3.0.0-rc releases so far. But maybe it's good enough to be used by this tool.

**Comment by Anifacted** [comment]
Nice input 👍 Will have a look at it

**Comment by Anifacted** [comment]
@maritz As of `0.9.0` this is now supported. The script will look in your `lerna.json` for glob configurations and will, of course, default to `[packages/*]`.

Please let me know if you run into any issues related to this or anything else. Again, thanks for the input.

Closing :)
