### ISSUE TITLE
Package Version is using ^version (Compatible with version) when selecting version from the list

### ISSUE THREAD

**Issue by shreyashah7** [Anifacted/lerna-update-wizard#84]
- Is there an option for selecting fixed version instead of **^** or **~** ?

**Comment by mleralec** [comment]
During the phase where you have to choose the version, you can use left/right arrow to add ^/~
cf `TIP: Move LEFT and RIGHT to change semver-prefix: ~ or ^`

**Comment by Anifacted** [comment]
Like @mleralec points out, you can specify this via the LEFT and RIGHT arrow keys :)

**Comment by rh78** [comment]
Hello is there a reason why I cannot select fixed version (not ~ and not ^)?

**Comment by shreyashah7** [comment]
@mleralec , I want to use the fix version not ~ and not ^. Even though i dont select ~/^, it appends ^ in my package.json file. How do i not add it? How do i select only a fix version?
